AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HiFromWorkshop

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    CodeUri: app/
    Runtime: ruby3.2
    Architectures:
      - arm64

Resources:
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scheduled.lambda_handler
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Enabled: true
