AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HiFromWorkshop

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    CodeUri: app/
    Runtime: ruby3.2
    Architectures:
      - arm64

Resources:
  ApplicationDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "type"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "timestamp"
          AttributeType: "N"
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "message"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "type"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      LocalSecondaryIndexes:
        - IndexName: "TimestampLSI"
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
            - AttributeName: "timestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      GlobalSecondaryIndexes:
        - IndexName: "MessageGSI"
          KeySchema:
            - AttributeName: "name"
              KeyType: "HASH"
            - AttributeName: "message"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  WebhooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: webhooks.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref ApplicationDB
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt ApplicationDB.Arn

Outputs:
  WebhooksUrl:
    Description: "Webhooks Function URL"
    Value:
      Fn::GetAtt: WebhooksFunctionUrl.FunctionUrl
