AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HiFromWorkshop

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  WebhooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: webhooks.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - arm64
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  WebhooksUrl:
    Description: "Webhooks Function URL"
    Value:
      Fn::GetAtt: WebhooksFunctionUrl.FunctionUrl
